#version: '3.8'

services:
  web:
    build: .
    ports:
      - "5002:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=backend/app.py
      - FLASK_ENV=development
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - trivia_network
    command: python backend/app.py

  question_generator:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - trivia_network
    dns:
      - 8.8.8.8  # Google's DNS
      - 8.8.4.4  # Google's secondary DNS
    command: python run.py
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=trivia_db
      - POSTGRES_USER=trivia_user
      - POSTGRES_PASSWORD=trivia_password
    ports:
      - "5432:5432"
    networks:
      - trivia_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trivia_user -d trivia_db"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  trivia_network:
    driver: bridge

volumes:
  postgres_data:
